### ISSUE TITLE
Make conda install work

### ISSUE THREAD

**Issue by captainrandom** [Public-Tree-Map/public-tree-map-data-pipeline#80] opened 2020-01-07 04:23 UTC
When creating a brand new local environment, dependencies won't install no matter what I do and I get the same error message as below.

**WHEN I**:
When I run `conda env update -f environment.yml`
in a brand new env. I get the following error message:

```Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - glib==2.56.2=hd408876_0
  - libgcc-ng==8.2.0=hdf63c60_1
  - giflib==5.1.4=h14c3975_1
  - geos==3.7.1=he6710b0_0
  - sqlalchemy==1.2.17=py37h7b6447c_0
  - dbus==1.13.6=h746ee38_0
  - mkl_random==1.0.2=py37hd81dba3_0
  - fiona==1.8.4=py37hc38cc03_0
  - pandas==0.24.1=py37he6710b0_0
  - freexl==1.0.5=h14c3975_0
  - sqlite==3.26.0=h7b6447c_0
  - shapely==1.6.4=py37h86c5351_0
  - curl==7.63.0=hbc83047_1000
  - gstreamer==1.14.0=hb453b48_1
  - libxml2==2.9.9=he19cac6_0
  - expat==2.2.6=he6710b0_0
  - libgdal==2.3.3=h2e7e64b_0
  - pyqt==5.9.2=py37h05f1152_2
  - openjpeg==2.3.0=h05c96fa_1
  - icu==58.2=h9c2bf20_1
  - gst-plugins-base==1.14.0=hbbd80ab_1
  - tk==8.6.8=hbc83047_0
  - libspatialite==4.3.0a=hb08deb6_19
  - libboost==1.67.0=h46d08c1_4
  - qt==5.9.7=h5867ecd_1
  - readline==7.0=h7b6447c_5
  - ncurses==6.1=he6710b0_1
  - fontconfig==2.13.0=h9420a91_0
  - bzip2==1.0.6=h14c3975_5
  - mkl_fft==1.0.10=py37ha843d7b_0
  - libuuid==1.0.3=h1bed415_2
  - hdf5==1.10.4=hb1b8bf9_0
  - gdal==2.3.3=py37hbb2a789_0
  - psycopg2==2.7.6.1=py37h1ba5d50_0
  - kealib==1.4.7=hd0c454d_6
  - libgfortran-ng==7.3.0=hdf63c60_0
  - zstd==1.3.7=h0b5b093_0
  - libedit==3.1.20181209=hc058e9b_0
  - numpy-base==1.15.4=py37hde5b4d6_0
  - libnetcdf==4.6.1=h11d0813_2
  - openssl==1.1.1a=h7b6447c_0
  - sip==4.19.8=py37hf484d3e_0
  - cairo==1.14.12=h8948797_3
  - libdap4==3.19.1=h6ec2957_0
  - freetype==2.9.1=h8a8886c_1
  - libffi==3.2.1=hd88cf55_4
  - pyproj==1.9.6=py37h14380d9_0
  - zlib==1.2.11=h7b6447c_3
  - libtiff==4.0.10=h2733197_2
  - proj4==5.2.0=he6710b0_1
  - tornado==5.1.1=py37h7b6447c_0
  - json-c==0.13.1=h1bed415_0
  - xerces-c==3.2.2=h780794e_0
  - libssh2==1.8.0=h1ba5d50_4
  - kiwisolver==1.0.1=py37hf484d3e_0
  - hdf4==4.2.13=h3ca952b_2
  - numpy==1.15.4=py37h7e9f1db_0
  - jpeg==9b=h024ee3a_2
  - libpq==11.1=h20c2e04_0
  - libxcb==1.13=h1bed415_1
  - libstdcxx-ng==8.2.0=hdf63c60_1
  - libpng==1.6.36=hbc83047_0
  - python==3.7.2=h0371630_0
  - libspatialindex==1.8.5=h20b78c2_2
  - pixman==0.36.0=h7b6447c_0
  - xz==5.2.4=h14c3975_4
  - krb5==1.16.1=h173b8e3_7
  - poppler==0.65.0=h581218d_1
  - libkml==1.3.0=h590aaf7_4
  - pcre==8.42=h439df22_0
  - scipy==1.2.0=py37h7c811a0_0
  - libcurl==7.63.0=h20c2e04_1000
  - matplotlib==3.0.2=py37h5429711_0
```

**I WANT TO**:
Not have an error when installing.

**Comment by captainrandom** [comment] 2020-01-07 06:07
The above error was generated on a mac. After reading the answer on stackoverflow, I found that this environment.yml file is os specific (namely linux).
https://stackoverflow.com/questions/55554431/conda-fails-to-create-environment-from-yml

I tried using the conda docker image and the install worked (which is debian based):
<img width="1298" alt="Screen Shot 2020-01-06 at 9 58 16 PM" src="https://user-images.githubusercontent.com/13500774/71872189-8ae7cf80-30d0-11ea-8809-5b637e5f6d2c.png">

This would indicate that the python install only works on linux which is problematic at best.

**Comment by ian-r-rose** [comment] 2020-01-07 17:28
Yes, this `environment.yml` was intended for linux machines. Really, it was only intended to be installed *on the default CircleCI agents*. It may work on other machines, but that wasn't really its purpose. The downside of relaxing the `environment.yml` here is that it can cause breakages in the CI environment if dependencies are released with inadvertent breaking changes.

Packaging is hard :/

**Comment by ian-r-rose** [comment] 2020-01-07 17:29
One thing we cant try is to chart a middle path by using the `--from-history` flag: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#exporting-an-environment-file-across-platforms

**Closed** 2020-04-17 16:43 UTC
Labels: help wanted
